# Type stubs for the sdflow pybind11 module (Kokkos cut-cell IBM Navier-Stokes solver).
#
# Editor / type-checker hints for the single-rank Python surface. `Solver` (staggered MAC) and
# `SolverColocated` (cell-centered) share one API — only the velocity-unknown placement differs — so
# the stub declares SolverColocated as carrying the same methods. Conventions: physical units (rho,
# mu, p); SDFs negative inside the solid; fields are Fortran-order (nx,ny,nz) float64 (x-fastest).
# Keep in sync with src/sdflow_bindings.cpp.
from __future__ import annotations

import numpy as np
import numpy.typing as npt

F64 = npt.NDArray[np.float64]

execution_space: str  # active Kokkos backend ("OpenMP", "Cuda", "HIP")

class Solver:
    """Staggered MAC cut-cell IBM incompressible Navier-Stokes solver (THE sdflow solver)."""

    def __init__(self, nx: int, ny: int, nz: int) -> None: ...
    # --- physical parameters (set before geometry / first step) ---
    def set_rho(self, rho: float) -> None: ...
    def set_mu(self, mu: float) -> None: ...
    def set_dt(self, dt: float) -> None: ...
    def set_body_force(self, fx: float, fy: float, fz: float) -> None: ...
    # --- advection ---
    def set_advection(self, on: bool) -> None: ...
    def set_advection_scheme(self, scheme: int) -> None: ...
    def set_implicit_advection(self, on: bool) -> None: ...
    # --- projection / outer iteration ---
    def set_incremental_pressure(self, on: bool) -> None: ...
    def set_pressure_warmstart(self, on: bool) -> None: ...
    def set_velocity_streams(self, on: bool) -> None: ...
    def set_outer_iterations(self, n: int) -> None: ...
    def set_outer_tolerance(self, tol: float) -> None: ...
    def last_outer_iterations(self) -> int: ...
    # --- solver tuning ---
    def set_velocity_solver_params(self, iters: int) -> None: ...
    def set_pressure_solver_params(self, iters: int) -> None: ...
    def set_pressure_multigrid(self, on: bool, levels: int = ...) -> None: ...
    def set_pressure_chebyshev(self, on: bool, max_iter: int = ..., rtol: float = ...) -> None: ...
    def set_pressure_pcg(self, on: bool, max_iter: int = ..., rtol: float = ...) -> None: ...
    def set_velocity_multigrid(self, on: bool, levels: int = ..., vcycles: int = ...) -> None: ...
    def last_pressure_iterations(self) -> int: ...
    # --- boundary conditions / geometry ---
    def set_domain_bc(
        self, face: int, type: int, vx: float = ..., vy: float = ..., vz: float = ...
    ) -> None: ...
    def set_domain_bc_profile(self, face: int, profile: F64) -> None: ...
    def set_pressure_geometry(self, sdf: F64) -> None: ...
    def set_solid(
        self, sdf: F64, cutcell_pressure: bool = ..., pressure_coarse: str = ...
    ) -> None: ...
    def set_state(self, u: F64, v: F64, w: F64) -> None: ...
    # --- stepping / readback ---
    def step(self) -> None: ...
    def get_u(self) -> F64: ...
    def get_v(self) -> F64: ...
    def get_w(self) -> F64: ...
    def get_p(self) -> F64: ...
    def max_open_divergence(self) -> float: ...
    def get_resolution(self) -> list[int]: ...
    def get_spacing(self) -> list[float]: ...
    # --- MPI mirror (single-rank stubs) ---
    def rank(self) -> int: ...
    def size(self) -> int: ...
    def bcast_from_root(self, value: object) -> object: ...

class SolverColocated(Solver):
    """Collocated (cell-centered) velocity variant; identical API to Solver (ABC projection)."""
