
import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Verification: Plane Poiseuille Flow\n",
    "\n",
    "This notebook verifies the solver accuracy by simulating gravity-driven flow between parallel plates (Plane Poiseuille Flow).\n",
    "\n",
    "We create a periodic domain with a solid slab in the center. The fluid wraps around the periodic boundaries at $y=0$ and $y=L$, effectively creating a channel of height $H = L - t_{slab}$.\n",
    "\n",
    "## Analytical Solution\n",
    "For a channel of height $H$ driven by body force $g_x$:\n",
    "$$ U_{avg} = \\frac{g H^2}{12 \\nu} $$\n",
    "$$ U_{max} = \\frac{1.5}{U_{avg}} = \\frac{g H^2}{8 \\nu} $$\n",
    "$$ u(y') = U_{max} \\left( 1 - \\left( \\frac{2 y'}{H} \\right)^2 \\right) $$\n",
    "where $y'$ is the distance from the channel center (which is at global $y=0$ in our periodic setup)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import time\n",
    "\n",
    "# Add build directory to path\n",
    "sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../build')))\n",
    "import pnm_backend\n",
    "\n",
    "os.makedirs('output', exist_ok=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_slab_sdf(nx, ny, nz, L, slab_thickness):\n",
    "    # Anisotropic resolution\n",
    "    # Domain size L is cubic for now, so L_x=L_y=L_z = L\n",
    "    # If L were a vector, we'd do dx = Lx/nx, etc.\n",
    "    dx = L / nx\n",
    "    dy = L / ny\n",
    "    dz = L / nz\n",
    "    \n",
    "    x = np.linspace(0, L, nx, endpoint=False) + 0.5 * dx\n",
    "    y = np.linspace(0, L, ny, endpoint=False) + 0.5 * dy\n",
    "    z = np.linspace(0, L, nz, endpoint=False) + 0.5 * dz\n",
    "    \n",
    "    X, Y, Z = np.meshgrid(x, y, z, indexing='ij')\n",
    "    \n",
    "    yc = L/2\n",
    "    # Distance to slab surface (walls at yc +/- t/2)\n",
    "    # Positive outside slab (fluid), Negative inside slab (solid)\n",
    "    # Actually pnm_backend assumes SDF < 0 is SOLID.\n",
    "    # So inside slab (y near yc), we want dist < 0.\n",
    "    # dist = |y - yc| - t/2\n",
    "    dist = np.abs(Y - yc) - slab_thickness/2.0\n",
    "    \n",
    "    return dist.ravel(order='F').astype(np.float32), (dx, dy, dz)\n",
    "\n",
    "def get_analytical_profile(y_coords, L, H, g, nu):\n",
    "    # y_coords: global y positions [0, L]\n",
    "    # Fluid channel is wrapped around y=0/L.\n",
    "    # Slab is at [L/2 - t/2, L/2 + t/2].\n",
    "    # Channel center is effectively at y=0 (or y=L).\n",
    "    # We map global y to channel coordinate y' in [-H/2, H/2].\n",
    "    \n",
    "    # If y < L/2: It is the 'bottom' half (connected to y=0). y' = y\n",
    "    # If y > L/2: It is the 'top' half (connected to y=L). y' = y - L\n",
    "    # Note: Walls are at y = (L-H)/2 and y = (L+H)/2 ? No.\n",
    "    # Slab t = L - H. Slab center L/2.\n",
    "    # Walls are at L/2 - t/2 = L/2 - (L-H)/2 = H/2.\n",
    "    # And L/2 + t/2 = L - H/2.\n",
    "    # So fluid is in [0, H/2] and [L - H/2, L].\n",
    "    \n",
    "    u_prof = np.zeros_like(y_coords)\n",
    "    U_max = (g * H**2) / (8.0 * nu)\n",
    "    \n",
    "    for i, y in enumerate(y_coords):\n",
    "        # Transform to centered coordinate y_prime\n",
    "        if y < L/2:\n",
    "            y_prime = y\n",
    "        else:\n",
    "            y_prime = y - L\n",
    "            \n",
    "        # Check if in fluid\n",
    "        if abs(y_prime) <= H/2:\n",
    "            u_prof[i] = U_max * (1.0 - (2.0 * y_prime / H)**2)\n",
    "        else:\n",
    "            u_prof[i] = 0.0 # In solid\n",
    "            \n",
    "    return u_prof\n",
    "\n",
    "def save_vti(filename, res_int3, spacing_float3, u, v, w, p):\n",
    "    \"\"\"Saves field data to VTI format.\"\"\"\n",
    "    nx, ny, nz = res_int3.x, res_int3.y, res_int3.z\n",
    "    dx, dy, dz = spacing_float3.x, spacing_float3.y, spacing_float3.z\n",
    "    \n",
    "    # Interpolate staggered velocity to cell centers for correct visualization\n",
    "    # u_stag(i,j,k) is at i-1/2. u_cc(i) = 0.5 * (u(i) + u(i+1))\n",
    "    \n",
    "    # Reshape using Fortran order to get (Nx, Ny, Nz) shape [x, y, z]\n",
    "    # This interprets the linear buffer (X-fast) correctly into [i,j,k]\n",
    "    u_grid = u.reshape((nx, ny, nz), order='F')\n",
    "    v_grid = v.reshape((nx, ny, nz), order='F')\n",
    "    w_grid = w.reshape((nx, ny, nz), order='F')\n",
    "    \n",
    "    # Check periodicity logic: pnm_backend uses periodic wrapping\n",
    "    # With shape [x, y, z]:\n",
    "    # Axis 0 is X\n",
    "    # Axis 1 is Y\n",
    "    # Axis 2 is Z\n",
    "    u_cc = 0.5 * (u_grid + np.roll(u_grid, -1, axis=0))\n",
    "    v_cc = 0.5 * (v_grid + np.roll(v_grid, -1, axis=1))\n",
    "    w_cc = 0.5 * (w_grid + np.roll(w_grid, -1, axis=2))\n",
    "    \n",
    "    # Flatten back to X-fast 1D streams for VTI writing\n",
    "    u_flat = u_cc.ravel(order='F')\n",
    "    v_flat = v_cc.ravel(order='F')\n",
    "    w_flat = w_cc.ravel(order='F')\n",
    "\n",
    "    with open(filename, 'w') as f:\n",
    "        f.write('<?xml version=\"1.0\"?>\\n')\n",
    "        f.write('<VTKFile type=\"ImageData\" version=\"0.1\" byte_order=\"LittleEndian\">\\n')\n",
    "        f.write(f'  <ImageData WholeExtent=\"0 {nx-1} 0 {ny-1} 0 {nz-1}\" Origin=\"0 0 0\" Spacing=\"{dx} {dy} {dz}\">\\n')\n",
    "        f.write(f'    <Piece Extent=\"0 {nx-1} 0 {ny-1} 0 {nz-1}\">\\n')\n",
    "        f.write('      <PointData Scalars=\"Pressure\" Vectors=\"Velocity\">\\n')\n",
    "        \n",
    "        f.write('        <DataArray type=\"Float32\" Name=\"Velocity\" NumberOfComponents=\"3\" format=\"ascii\">\\n')\n",
    "        for i in range(len(u_flat)):\n",
    "            f.write(f\"{u_flat[i]} {v_flat[i]} {w_flat[i]} \")\n",
    "        f.write('\\n        </DataArray>\\n')\n",
    "        \n",
    "        f.write('        <DataArray type=\"Float32\" Name=\"u\" NumberOfComponents=\"1\" format=\"ascii\">\\n')\n",
    "        for val in u_flat:\n",
    "            f.write(f\"{val} \")\n",
    "        f.write('\\n        </DataArray>\\n')\n",
    "\n",
    "        f.write('        <DataArray type=\"Float32\" Name=\"v\" NumberOfComponents=\"1\" format=\"ascii\">\\n')\n",
    "        for val in v_flat:\n",
    "            f.write(f\"{val} \")\n",
    "        f.write('\\n        </DataArray>\\n')\n",
    "\n",
    "        f.write('        <DataArray type=\"Float32\" Name=\"w\" NumberOfComponents=\"1\" format=\"ascii\">\\n')\n",
    "        for val in w_flat:\n",
    "            f.write(f\"{val} \")\n",
    "        f.write('\\n        </DataArray>\\n')\n",
    "        \n",
    "        f.write('        <DataArray type=\"Float32\" Name=\"Pressure\" NumberOfComponents=\"1\" format=\"ascii\">\\n')\n",
    "        for val in p:\n",
    "            f.write(f\"{val} \")\n",
    "        f.write('\\n        </DataArray>\\n')\n",
    "        \n",
    "        f.write('      </PointData>\\n')\n",
    "        f.write('    </Piece>\\n')\n",
    "        f.write('  </ImageData>\\n')\n",
    "        f.write('</VTKFile>\\n')\n",
    "    print(f\"Saved {filename}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "    return y_coords, u_profile, u_ana\n",
    "\n",
    "def run_poiseuille(res_tuple, save_output=False, filename=None):\n",
    "    nx, ny, nz = res_tuple\n",
    "    L = 1.0\n",
    "    slab_thickness = 0.2\n",
    "    H = L - slab_thickness\n",
    "    \n",
    "    sdf_values, spacing = generate_slab_sdf(nx, ny, nz, L, slab_thickness)\n",
    "    dx, dy, dz = spacing\n",
    "    \n",
    "    sdf_data = pnm_backend.SDFData(\n",
    "        sdf_values, \n",
    "        pnm_backend.int3(nx, ny, nz),\n",
    "        pnm_backend.float3(0,0,0),\n",
    "        pnm_backend.float3(dx, dy, dz)\n",
    "    )\n",
    "    solver = pnm_backend.CFDSolver(\n",
    "        pnm_backend.int3(nx, ny, nz), \n",
    "        pnm_backend.float3(dx, dy, dz)\n",
    "    )\n",
    "    solver.initialize(sdf_data)\n",
    "    \n",
    "    rho = 1.0\n",
    "    nu = 0.01\n",
    "    g_x = 1.0e-2\n",
    "    solver.set_body_force(pnm_backend.float3(g_x, 0, 0))\n",
    "    # Time step limited by smallest cell size\n",
    "    dt = 0.1 * min(dx, dy, dz)\n",
    "    \n",
    "    print(f\"Running Grid={nx}x{ny}x{nz}...\")\n",
    "    for i in range(5000):\n",
    "        solver.step(dt, rho, nu, 20, 1e-5)\n",
    "        # Simple fixed steps or convergence check\n",
    "        if i > 0 and i % 100 == 0:\n",
    "            # Minimal output to keep notebook clean\n",
    "            pass\n",
    "            \n",
    "    # Extract Profile\n",
    "    # Get full U field\n",
    "    u_flat = np.array(solver.get_u())\n",
    "    u_grid = u_flat.reshape((nx, ny, nz), order='F') # [x, y, z]\n",
    "    \n",
    "    # Extract line profile at mid-X, mid-Z, along Y\n",
    "    ix = nx // 2\n",
    "    iz = nz // 2\n",
    "    u_profile = u_grid[ix, :, iz]\n",
    "    \n",
    "    # Analytical Profile\n",
    "    # Y coordinates correspond to cell centers in Y direction\n",
    "    y_coords = np.linspace(0, L, ny, endpoint=False) + 0.5 * dy\n",
    "    u_ana = get_analytical_profile(y_coords, L, H, g_x, nu)\n",
    "    \n",
    "    if save_output and filename:\n",
    "        v = np.array(solver.get_v())\n",
    "        w = np.array(solver.get_w())\n",
    "        p = np.array(solver.get_p())\n",
    "        save_vti(filename, pnm_backend.int3(nx, ny, nz), pnm_backend.float3(dx, dy, dz), u_flat, v, w, p)\n",
    "    \n",
    "    return y_coords, u_profile, u_ana"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "resolutions = [(16, 16, 16), (16, 32, 16), (16, 64, 16), (16, 128, 16)]\n",
    "results = {}\n",
    "\n",
    "plt.figure(figsize=(10, 6))\n",
    "\n",
    "for res in resolutions:\n",
    "    nx, ny, nz = res\n",
    "    filename = f'output/poiseuille_{nx}x{ny}x{nz}.vti'\n",
    "    y, u_sim, u_ana = run_poiseuille(res, save_output=True, filename=filename)\n",
    "    results[res] = (y, u_sim, u_ana)\n",
    "    \n",
    "    plt.plot(y, u_sim, 'o', label=f'Sim Ny={ny} (Nx=Nz=16)')\n",
    "    if res == resolutions[-1]: # Plot analyt only once or for best res\n",
    "        plt.plot(y, u_ana, 'k-', linewidth=2, label='Analytical')\n",
    "\n",
    "plt.xlabel('y')\n",
    "plt.ylabel('Velocity u(y)')\n",
    "plt.title('Poiseuille Flow Profile verification')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "plt.savefig('output/poiseuille_profile.png')\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open('notebooks/verify_poiseuille.ipynb', 'w') as f:
    json.dump(notebook_content, f, indent=1)

print("Notebook generated: notebooks/verify_poiseuille.ipynb")
