
import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Verification: Flow Past Periodic Array of Spheres\n",
    "\n",
    "This notebook verifies the CFD solver by simulating flow through a simple cubic array of spheres at low Reynolds number ($Re \\approx 0.01$).\n",
    "\n",
    "We compare the computed Drag Coefficient ($K$) against reference values from Zick & Homsy (1982) and Sangani & Acrivos (1982).\n",
    "\n",
    "## Objectives\n",
    "1. **Parameter Sweep**: Calculate $K$ for solid volume fractions $\\phi \\in [0.05, 0.5]$.\n",
    "2. **Grid Convergence**: Verify numerical convergence for the dense case $\\phi=0.5$.\n",
    "3. **Visualization**: Export flow fields to VTI and plot results."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import time\n",
    "\n",
    "# Add build directory to path to import pnm_backend\n",
    "sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../build')))\n",
    "import pnm_backend\n",
    "\n",
    "# Ensure output directory exists\n",
    "os.makedirs('output', exist_ok=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Helper Functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_sc_sdf(phi, res_n, L=1.0):\n",
    "    \"\"\"Generates Signed Distance Field for a Simple Cubic array of spheres.\"\"\"\n",
    "    # Use (Nx, Ny, Nz) shape with Fortran-order (x varies fastest) for consistency with user preference\n",
    "    dx = L/res_n\n",
    "    x = np.linspace(0, L, res_n, endpoint=False) + 0.5 * dx\n",
    "    y = np.linspace(0, L, res_n, endpoint=False) + 0.5 * dx\n",
    "    z = np.linspace(0, L, res_n, endpoint=False) + 0.5 * dx\n",
    "    \n",
    "    # indexing='ij' gives shape (Nx, Ny, Nz)\n",
    "    X, Y, Z = np.meshgrid(x, y, z, indexing='ij')\n",
    "    \n",
    "    R = (phi * 3.0 / (4.0 * np.pi))**(1.0/3.0) * L\n",
    "    \n",
    "    xc, yc, zc = L/2, L/2, L/2\n",
    "    dist = np.sqrt((X - xc)**2 + (Y - yc)**2 + (Z - zc)**2)\n",
    "    sdf = dist - R\n",
    "    \n",
    "    # ravel(order='F') ensures we flatten (x,y,z) as x-fast, y-med, z-slow\n",
    "    # which matches the C++ linear index: idx = z*ny*nx + y*nx + x\n",
    "    return sdf.ravel(order='F').astype(np.float32), R, (dx, dy, dz)\n",
    "\n",
    "def get_analytical_k(phi):\n",
    "    \"\"\"Returns reference Drag Factor K from Sangani & Acrivos (1982) for Simple Cubic.\"\"\"\n",
    "    phis = np.array([0.05, 0.10, 0.20, 0.30, 0.40, 0.50])\n",
    "    ks   = np.array([4.95, 6.10, 9.10, 13.6, 21.6, 39.5])\n",
    "    if phi < phis[0]: return 1.0 # Dilute limit approximation\n",
    "    return np.interp(phi, phis, ks)\n",
    "\n",
    "def save_vti(filename, res_int3, spacing_float3, u, v, w, p):\n",
    "    \"\"\"Saves field data to VTI format.\"\"\"\n",
    "    nx, ny, nz = res_int3.x, res_int3.y, res_int3.z\n",
    "    dx, dy, dz = spacing_float3.x, spacing_float3.y, spacing_float3.z\n",
    "    \n",
    "    # Interpolate staggered velocity to cell centers for correct visualization\n",
    "    # u_stag(i,j,k) is at i-1/2. u_cc(i) = 0.5 * (u(i) + u(i+1))\n",
    "    \n",
    "    # Reshape using Fortran order to get (Nx, Ny, Nz) shape [x, y, z]\n",
    "    # This interprets the linear buffer (X-fast) correctly into [i,j,k]\n",
    "    u_grid = u.reshape((nx, ny, nz), order='F')\n",
    "    v_grid = v.reshape((nx, ny, nz), order='F')\n",
    "    w_grid = w.reshape((nx, ny, nz), order='F')\n",
    "    \n",
    "    # Check periodicity logic: pnm_backend uses periodic wrapping\n",
    "    # With shape [x, y, z]:\n",
    "    # Axis 0 is X\n",
    "    # Axis 1 is Y\n",
    "    # Axis 2 is Z\n",
    "    u_cc = 0.5 * (u_grid + np.roll(u_grid, -1, axis=0))\n",
    "    v_cc = 0.5 * (v_grid + np.roll(v_grid, -1, axis=1))\n",
    "    w_cc = 0.5 * (w_grid + np.roll(w_grid, -1, axis=2))\n",
    "    \n",
    "    # Flatten back to X-fast 1D streams for VTI writing\n",
    "    u_flat = u_cc.ravel(order='F')\n",
    "    v_flat = v_cc.ravel(order='F')\n",
    "    w_flat = w_cc.ravel(order='F')\n",
    "\n",
    "    with open(filename, 'w') as f:\n",
    "        f.write('<?xml version=\"1.0\"?>\\n')\n",
    "        f.write('<VTKFile type=\"ImageData\" version=\"0.1\" byte_order=\"LittleEndian\">\\n')\n",
    "        f.write(f'  <ImageData WholeExtent=\"0 {nx-1} 0 {ny-1} 0 {nz-1}\" Origin=\"0 0 0\" Spacing=\"{dx} {dy} {dz}\">\\n')\n",
    "        f.write(f'    <Piece Extent=\"0 {nx-1} 0 {ny-1} 0 {nz-1}\">\\n')\n",
    "        f.write('      <PointData Scalars=\"Pressure\" Vectors=\"Velocity\">\\n')\n",
    "        \n",
    "        f.write('        <DataArray type=\"Float32\" Name=\"Velocity\" NumberOfComponents=\"3\" format=\"ascii\">\\n')\n",
    "        # Writing loop can be slow for large files in python, but acceptable for validation cases\n",
    "        for i in range(len(u_flat)):\n",
    "            f.write(f\"{u_flat[i]} {v_flat[i]} {w_flat[i]} \")\n",
    "        f.write('\\n        </DataArray>\\n')\n",
    "        \n",
    "        f.write('        <DataArray type=\"Float32\" Name=\"Pressure\" NumberOfComponents=\"1\" format=\"ascii\">\\n')\n",
    "        for val in p:\n",
    "            f.write(f\"{val} \")\n",
    "        f.write('\\n        </DataArray>\\n')\n",
    "        \n",
    "        f.write('      </PointData>\\n')\n",
    "        f.write('    </Piece>\\n')\n",
    "        f.write('  </ImageData>\\n')\n",
    "        f.write('</VTKFile>\\n')\n",
    "    print(f\"Saved {filename}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Simulation Kernel"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class SimulationRunner:\n",
    "    def __init__(self, phi, res_n, L=1.0):\n",
    "        self.phi = phi\n",
    "        self.res_n = res_n\n",
    "        self.L = L\n",
    "        \n",
    "        self.sdf_values, self.R, self.spacing_tuple = generate_sc_sdf(phi, res_n, L)\n",
    "        self.dx, self.dy, self.dz = self.spacing_tuple\n",
    "        \n",
    "        # Setup Data Objects\n",
    "        self.sdf_data = pnm_backend.SDFData(\n",
    "            self.sdf_values, \n",
    "            pnm_backend.int3(res_n, res_n, res_n),\n",
    "            pnm_backend.float3(0,0,0),\n",
    "            pnm_backend.float3(self.dx, self.dy, self.dz)\n",
    "        )\n",
    "        self.solver = pnm_backend.CFDSolver(\n",
    "            pnm_backend.int3(res_n, res_n, res_n), \n",
    "            pnm_backend.float3(self.dx, self.dy, self.dz)\n",
    "        )\n",
    "        self.solver.initialize(self.sdf_data)\n",
    "        \n",
    "        # Parameters (Low Re)\n",
    "        self.rho = 1e-3\n",
    "        self.mu = 1e0\n",
    "        self.f_mag = 1.0\n",
    "        self.solver.set_body_force(pnm_backend.float3(self.f_mag, 0, 0))\n",
    "        self.solver.set_rho(self.rho)\n",
    "        self.solver.set_mu(self.mu)\n",
    "        \n",
    "        # Solver Parameters for Implicit Scheme\n",
    "        self.solver.set_pressure_solver_params(100, 1e-16)\n",
    "        self.solver.set_velocity_solver_params(200, 1e-16)\n",
    "\n",
    "    def run(self, dt=1.0, max_steps=10000, save_output=False, filename=None):\n",
    "        # Explicit limit is roughly 0.5*dx^2/nu ~ 0.5 * (1/64)^2 / 0.01 ~ 0.01\n",
    "        # We use a much larger step to speed up convergence to steady state.\n",
    "        \n",
    "        u_mean_history = []\n",
    "        \n",
    "        print(f\"Running phi={self.phi:.3f}, Res={self.res_n}^3, dt={dt:.4f}...\")\n",
    "        \n",
    "        start_time = time.time()\n",
    "        for i in range(max_steps):\n",
    "            # Use Implicit Step\n",
    "            self.solver.step(dt)\n",
    "            \n",
    "            if i % 50 == 0:\n",
    "                u_field = np.array(self.solver.get_u())\n",
    "                u_mean = np.mean(u_field)\n",
    "                u_mean_history.append(u_mean)\n",
    "                \n",
    "                if len(u_mean_history) > 5:\n",
    "                    # Relative change convergence check\n",
    "                    if abs(u_mean_history[-1]) > 1e-12:\n",
    "                        err = abs(u_mean_history[-1] - u_mean_history[-2]) / abs(u_mean_history[-1])\n",
    "                        if err < 1e-5:\n",
    "                            print(f\"  Converged at step {i}. Mean Vel = {u_mean:.6e}\")\n",
    "                            break\n",
    "        \n",
    "        elapsed = time.time() - start_time\n",
    "        u_field = np.array(self.solver.get_u())\n",
    "        U_sup = np.mean(u_field)\n",
    "        \n",
    "        # Calculate K\n",
    "        F_drag = self.f_mag * (self.L**3)\n",
    "        K = F_drag* (1-self.phi) / (6.0 * np.pi * self.mu * self.R * U_sup)\n",
    "        \n",
    "        print(f\"  K_sim = {K:.4f} (Time: {elapsed:.2f}s)\")\n",
    "        \n",
    "        if save_output and filename:\n",
    "            v = np.array(self.solver.get_v())\n",
    "            w = np.array(self.solver.get_w())\n",
    "            p = np.array(self.solver.get_p())\n",
    "            save_vti(filename, pnm_backend.int3(self.res_n, self.res_n, self.res_n), pnm_backend.float3(self.dx, self.dy, self.dz), u_field, v, w, p)\n",
    "            \n",
    "        return K, U_sup"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Parameter Sweep"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "phis = [0.05, 0.10, 0.20, 0.30, 0.40, 0.50]\n",
    "res_n = 128\n",
    "\n",
    "results = []\n",
    "\n",
    "for phi in phis:\n",
    "    simulator = SimulationRunner(phi, res_n)\n",
    "    k_sim, u_sup = simulator.run(save_output=True, filename=f\"output/final_phi_{phi:.2f}.vti\")\n",
    "    k_ref = get_analytical_k(phi)\n",
    "    results.append({\n",
    "        'phi': phi,\n",
    "        'k_sim': k_sim,\n",
    "        'k_ref': k_ref,\n",
    "        'error': 100*(k_sim - k_ref)/k_ref\n",
    "    })\n",
    "\n",
    "# Output Table\n",
    "print(\"\\nSummary Results:\")\n",
    "print(f\"{'Phi':<10} {'K_sim':<10} {'K_ref':<10} {'Error %':<10}\")\n",
    "print(\"-\"*40)\n",
    "for res in results:\n",
    "    print(f\"{res['phi']:<10.3f} {res['k_sim']:<10.4f} {res['k_ref']:<10.4f} {res['error']:<10.2f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Plotting\n",
    "phi_vals = [r['phi'] for r in results]\n",
    "k_sims = [r['k_sim'] for r in results]\n",
    "k_refs = [r['k_ref'] for r in results]\n",
    "\n",
    "plt.figure(figsize=(8, 6))\n",
    "plt.plot(phi_vals, k_refs, 'k--o', label='Sangani & Acrivos (Ref)')\n",
    "plt.plot(phi_vals, k_sims, 'r-s', label='Simulation (Global P)')\n",
    "plt.xlabel('Solid Volume Fraction $\\phi$')\n",
    "plt.ylabel('Dimensionless Drag Factor $K$')\n",
    "plt.title('Drag in Simple Cubic Array')\n",
    "plt.grid(True)\n",
    "plt.legend()\n",
    "plt.savefig('output/param_sweep_plot.png')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Grid Convergence Study (phi=0.5)\n",
    "We test resolution effects for the densest case."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "phi_dense = 0.50\n",
    "resolutions = [32, 64, 96]\n",
    "\n",
    "convergence_results = []\n",
    "\n",
    "print(f\"Running Grid Convergence for phi={phi_dense}...\")\n",
    "for res in resolutions:\n",
    "    simulator = SimulationRunner(phi_dense, res)\n",
    "    k_sim, _ = simulator.run(save_output=False)\n",
    "    convergence_results.append((res, k_sim))\n",
    "\n",
    "    print(\"\\nGrid Convergence Results (phi=0.5):\")\n",
    "    print(f\"{'N':<5} {'K_sim':<10}\")\n",
    "    print(\"-\" * 15)\n",
    "    for r in convergence_results:\n",
    "        print(f\"{r[0]:<5} {r[1]:<10.4f}\")\n",
    "\n",
    "# Plot Convergence\n",
    "res_vals = [r[0] for r in convergence_results]\n",
    "k_vals = [r[1] for r in convergence_results]\n",
    "\n",
    "plt.figure(figsize=(8, 6))\n",
    "plt.plot(res_vals, k_vals, 'b-o')\n",
    "plt.xlabel('Grid Resolution N')\n",
    "plt.ylabel('K Factor')\n",
    "plt.title(f'Grid Convergence ($\\phi={phi_dense}$)')\n",
    "plt.grid(True)\n",
    "plt.savefig('output/grid_convergence.png')\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open('notebooks/verification_periodic_spheres.ipynb', 'w') as f:
    json.dump(notebook_content, f, indent=1)

print("Notebook generated: notebooks/verification_periodic_spheres.ipynb")
